name: NeuraShield Security Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.py'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  security-scan:
    uses: AaryaSoni-web/neurashield-ai/.github/workflows/reusable-analysis.yml@main
    with:
      source-repo: ${{ github.repository }}
      pr-number: ${{ github.event.pull_request.number }}
      issue-number: ${{ github.event.issue.number }}
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

